#!/bin/sh
git clone https://github.com/oldwife/shell-notes /tmp/shell-notes
cd /tmp/shell-notes
nvim git-test-notes
cp -i /tmp/shell-notes ~/.local/bin/
git add .
git commit --message "$(date)"
git push -uf origin main
