#!/bin/sh
internet="$(ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null && echo "online" || echo "offline")"
#internet="offline"

get_latest_version(){
	git clone https://github.com/oldwife/shell-notes /tmp/shell-notes
	file_path=/tmp/shell-notes/git-test-notes
}

if [[ "$internet" == "online" ]];then
	get_latest_version
else
	file_path=$0
fi

cat "$0" > ~/.cache/noteslocal.bak

header="$( cat "$file_path" | head -n +44 )" #:<<NOTEBLOCK
notes="$( cat "$file_path" | tail -n +45 | head -n -1 | gpg -dq )" #-----BEGIN PGP MESSAGE
echo "$notes" > /tmp/shell-notes.md
nvim /tmp/shell-notes.md
build_file() {
	echo "$header"
	cat /tmp/shell-notes.md | gpg -ac -o-
	echo "NOTEBLOCK"
}
build_file > "$file_path"
rm -rf /tmp/shell-notes.md

upload_notes(){
	cp -i /tmp/shell-notes/git-test-notes ~/.local/bin/
	cd /tmp/shell-notes
	git add .
	git commit --message "$(date)"
	git push -uf origin main
	rm -rf /tmp/shell-notes
}

if [[ "$internet" == "online" ]];then
	upload_notes
fi

# LINE 30
:<<NOTEBLOCK
-----BEGIN PGP MESSAGE-----

jA0ECQMI48Y2eg5MzLn50kIBvhHl0j+HbODW/HrTYWfDEYoEDn6xDxC5eN6V/aiw
ZtMET2UyQ8tBgWIoGyyyHgFdGbgaSZIKabU6EBYnazvJvqs=
=V4B5
-----END PGP MESSAGE-----
NOTEBLOCK
