#!/bin/sh
internet="$(ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null && echo "online" || echo "offline")"
#internet="offline"

get_latest_version(){
	git clone https://github.com/oldwife/shell-notes /tmp/shell-notes
	file_path=/tmp/shell-notes/git-test-notes
}

if [[ "$internet" == "online" ]];then
	get_latest_version
else
	file_path=$0
fi

cat "$0" > ~/.cache/noteslocal.bak

header="$( cat "$file_path" | head -n +44 )" #:<<NOTEBLOCK
notes="$( cat "$file_path" | tail -n +45 | head -n -1 | gpg -dq )" #-----BEGIN PGP MESSAGE
echo "$notes" > /tmp/shell-notes.md
nvim /tmp/shell-notes.md
build_file() {
	echo "$header"
	cat /tmp/shell-notes.md | gpg -ac -o-
	echo "NOTEBLOCK"
}
build_file > "$file_path"
rm -rf /tmp/shell-notes.md

upload_notes(){
	cp -i /tmp/shell-notes/git-test-notes ~/.local/bin/
	cd /tmp/shell-notes
	git add .
	git commit --message "$(date)"
	git push -uf origin main
	rm -rf /tmp/shell-notes
}

if [[ "$internet" == "online" ]];then
	upload_notes
fi

# LINE 30
:<<NOTEBLOCK
-----BEGIN PGP MESSAGE-----

jA0ECQMIs8yiB4omiB750uoB0kYC82vmVPV3sbsorn8/4T9QHODoKEQuYWjVpLW5
+JJiHzHSmLj/LfaylrYhhwhdsF/4xv0c8o++Q2Jy1K3jGdetheLseulygQvN+k3i
SPuvfT0Kcn4HgJ2MNeQ42s0b8YwmIBp4pakufkfz7xby1L7OPjdGXTwFqd7SatU+
2GsFGkJy+qVzBZ8kI5p4flbbWUTbbFzK4GCyQ7UaJqVLinS39G33nzSquEW9Q8kd
zpel/FWIgOIKJ3s6Ulbr048ZUy9NsyP7sN9mIQCWMu7ZBNGK0Q+sXiRpbUAzwDwE
ZDJJoaSRXKwFXy2fS7R0JAOOanokEmOyZzpDnKEz1U496PwA+UJLec9S3qluLRAO
rh4R/cIHbIkUUfasZWyBS2O8op+4PBkEFyGtIoTDskfIoX1g0gHypINgttT4L+X1
9XXW6lNsO0N77aRbVBg1gcTrv7yzfR2mbBC9/y7OVsN1GGYqyQTrSnHgj5QSiOrC
wiCJ+zIjIlLPgwnXPF6d3Fv5qz86eBkMLseBQlq5nxADK0WGLgUNCv8ECunpa6WW
aecDIM/+BQRMCnNohgCQOUcX0MnUniTOaRWIOhEfRqfShUN4tqz2AL+2LiRuPtG2
1M4w7mjYUaJjM5xnLOFT0G9KkCwJ5VZFircdjUjOwaLhaOEdMJj+4h4BB9kb9han
2K8slKjZowP8ORGkWeojeeTEGHIFASqwMe5jiBI5A9P4m8T+aj1cK0QotIaHf4Y3
q4AQ7QXqp/q8CAu/Fjmm81nNJI95uk8YdU/HDZ1XDUmL4u3v9/jh4AXYoies/0d2
r0avW3ldlEZSuXHFbXSyVZJuLRfFaqi1a6is6KlLHb2QEbKhZpUf9jECYxH1SxVO
FUtpjn+XW9lfqNKxg7Vq6Hg71w5kOYg6BgkxyZkp0jN1EyuiCBZf6giqbGcdNC+W
khnpKZcmIHKFwmIyi12T5BJnlF65vZoXvjNXTsF0HO2PW0Nh/fMW3GcnrpZ16nas
yF3bvn3cEY+9aJw80qCIT8/Lsqq5WIYVq0SORi53VYcVKm0r2H5qIrI4bJ0m90dB
xpeZnFRu1QTJt/kig8Xl53kj290ooY34b5ya2fHiYy1CYXHeX+aI1/VbARJtWUxS
VuR1I5RJLbt3ZMpHz3fj9HDBuTXUfh23EyUPVFZ+WCJBiHwUCDVVQpL5TVy1SMd0
/fVO5/2pB8xCKEZVZRrnlofug/aFBmQr+1AaiT+51fkDpHq3aapDmT3h3QNkIX0O
V7xHFT9ngwvxzfsla1fzfv4MHYDwc5XTVnOpjKbA1hAHaeuOQSx2To3zyedEXfhT
F7DVcY9lvv8BCvcLWoCQVsRMvvBJc6v/JPhh8nH0NkFh6m7TsnvGfS8W2aCzP7tX
o+jHxxRg7FQ1R0WoLYsCCwL1MjSSUc47r6BDPirSR+HFBAI3QDVd6Gc4l0blB+lB
LgLh/5I6wYDGBYC0jzqHRxY4yi0k9Mzei8waHlRv8gdrwX3/vWMH0idEW4pviUR7
msSK6cMDlmGKHBW9jUdX9WQR0wCbXnjwBjeTUBuXIm4xyA19R0K5MMPmF7g8Vllg
78JDp0KukLHe2vLEkzAdL45p3aWWEwB6RAW4krRLUwDNOVJ5/p4y84SuXVFASXsZ
jOIrUtzLcSeFM+CtAxL8D83/od5C3tETlubPmEWKubZl2AqBgTbBdvz/hArWo+55
yaLrAJ+a4w+kH/akiUXLtIiH6azmkJNxutlsGEr2EvUlO32Vu1Swy/2ePOkziByu
SwdoYIQxzEIqcdsYu7LxSua2ucdNboTJC5IUA+pnkpJiOXDLi5Helm0jacHVPnKa
VJadvVmj0F0VSUFoyJcuGzu9DO3GsKNBvXhWlsxyGL7yZe/TpuDS/F+WmYbzcuEY
tWlJsKrV52wMgdca0u9m27ZC3srQOgCeyb4OjSrEyr1rooLVC0c6mEnADus2Jax3
i0vyk8+SqC3XM04ToN0ILZfoZQkgYsR9Qb4Vh7QkRQgSSgICql75n/Im0IlG9bAo
qy/5KWtfCJdYjL+7QpkLPMioE1QrdsTi/UzYZrqlIibvnjCBTxp/9yVFg+Vp+wm+
IQUaqvWaYx8ob4PAVGK51Fugmd2udJkoTqMa7PFZ87fCRc+GKo/uEZjWpdGMEQ43
9k08Md+f3b55z0DWwwiClfh1fZduHbWNDGQV0SY8CiozAZAJqr6Qkg0ZHS3qD62v
1q0puCmLJElh4PtRy9KqAjrRU7Tv0FcmIn2WGMu/nyAOkGYevzPSXdN4FSMe+dg0
3ffHRqOShE4pYylZE4c1ywM3YUucTXYLNt9DOpjxvXXr95E2FpicxNv47o5B7iFA
U5Kj43g7zTx/KiMfdFJpbgFhY/lE2kuxT/tAgV7hhSWA+Nm9YXVAERnZgJQVTlgd
LC13BijTF1YMZ52TkGkeSXhpCwCDMbTMblg7Q12oDoD+kynDnhSMxlgJzv5HYfIl
sD7DH0Sc6P/dD4zUAEUvvglEelZDtknFqz9pYJ4HV/VeLO+y3cqwACk91jeOXWuX
/1SxrYUM7XfOlcc0eD3A8iVICVI7+Cu/9O5UIAKXu2MVtWOi7MEjvMVPRe+bld4M
uINXyE8N97odMWWmuf9Fr9Hsk1JzEa6ptOeBxJfxZzKwBkba5wYjPrm0t++D6SIh
uqYBKFv/rQwdJgUhKwRcizzm9Ep7FmvSJNxzTNKN9ghxA7kVbsesv1RXqMc3fEQM
opjAqo8oQ6GdIj9kOWIJUTiSCMhmSn0BjdzV34o96pfJC3eg9u1tPw2DcPtLftab
sXq2QRoVlEPbxUQBN4GTKHTc+LllKmx8u90yFuw+1YycZJeJ7BDSLwxMr9CZozcR
+7MNmyZt85/ValxvF5JDPzC41kVp0CNR1STRWxS8Y8Zudcw7CxTBtyHdFtdmv/9l
zN6zzGZOYLEhmKwJ9iMtYoBbyafKBhVOaZ1VHvnKihFEO2yXg31H1BirJYYcbpaw
ZZBdUFjNQNWz5R2C1pLQBIA/RvD2F2U3E3gcYtVsWYaToORa/pSv3rNWxXBuxd0A
ic0CcIKfH+WgxIXHxx/hkNiwRA3X2JWZM6BcBhB2MG6d0ciAM9XS1omIB3gkhcJS
yGkI3uTl76HnN/oawdFv113+svj90HocwkKOeAYT+0t0VRSPGzDPfDVobHNsT7tN
30crdfzw6JNcxubjUSN/yiyjqjYQCWpdOBijnAwS
=ZiN5
-----END PGP MESSAGE-----
NOTEBLOCK
