#!/bin/sh
internet="$(ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null && echo "online" || echo "offline")"
#internet="offline"

get_latest_version(){
	git clone https://github.com/oldwife/shell-notes /tmp/shell-notes
	file_path=/tmp/shell-notes/notes
}

if [[ "$internet" == "online" ]];then
	get_latest_version
else
	file_path=$0
fi

cat "$0" > ~/.cache/noteslocal.bak

header="$( cat "$file_path" | head -n +44 )" #:<<NOTEBLOCK
notes="$( cat "$file_path" | tail -n +45 | head -n -1 | gpg -dq )" #-----BEGIN PGP MESSAGE
echo "$notes" > /tmp/notes.sh
nvim /tmp/notes.sh
build_file() {
	echo "$header"
	cat /tmp/notes.sh | gpg -ac -o-
	echo "NOTEBLOCK"
}
build_file > "$file_path"
rm -rf /tmp/notes.sh

upload_notes(){
	cp -i /tmp/shell-notes/notes ~/.local/bin/
	cd /tmp/shell-notes
	git add .
	git commit --message "$(date)"
	git push -uf origin main
	rm -rf /tmp/shell-notes
}

if [[ "$internet" == "online" ]];then
	upload_notes
fi

# LINE 30
:<<NOTEBLOCK
-----BEGIN PGP MESSAGE-----

jA0ECQMIKzhYTDNciL/50uoB1hH+IznCRYe1xjYFlG3k4tgiPEzrYH7k6dN0/NnC
ZJusPxeaq4APq1eT7lJBWQpVobqtHBBXGGRyGIt/mKrXbF6hqgcL9PWuRBbn6JpB
vnYE2XCwLDqsYsFqdDryNWd7yNSEGsmwGqLxIFs2ahjK+D9BcVQ14qj42Eyk4wcy
8qtEo0WummPzYyKRKXOEDOEctUABf0aisqAoVxI4IAxcWfdEEx3F3hN6LkUO8Q0l
lJCJqDRmmF2vtM3FGPyQZFbPrpRVtsyXbzXMKnzb2mQN6wpQBHwkHOlv7Zsx3J7F
Y/IIzu2PodRQdksJirMhNUZPzrYmWWR9iprV84i419xXDIdHTA6jup5tQwtuSAd4
cXdZQ4ySW8xqh/kWfcqNZmhOx34rWMMXZ7y8xMZAWSt4w0elpR1cYiwR6F2Jwrii
TvnmHt0+L9vz4bpRmaGvGMCZcyA5qtmnL2etCFpXkx74TUpe5TVkSJhxo6t0ZGE3
hZmbzDnEVj+rH+KWUYr5wm8T6eESAOzlowxlEO00D5aXNqu9Oo4NjCYBa9YkkvO+
5xUjpy4QBYLsRK/YcUj7TUGU57Q6nV0534mlBpEqc6zmcwazwecq7AtL3jngwXON
enY5ptuLphUzOpVkliKDlacJRgtdCUYU7bGfaCjO5ZpI3cupP+dJsaIwgDhfSSQu
eyacs0+FqVXGutpFXHLlfKs71noYzittPds39n1dJE5t4STw47Gj1p2NZz+aedmA
422PaODIDsd9H867FmX7oViMj0G3vHRTOrV1ypmUljv1/gDkkVFRmejFS0Cx4viN
91wGlzaZfFrNnev4UPhmgl+5ilyuMVXkgwD+Amv2Ca0PkcbIAlAuayQ4BlaFRVwP
hW9eQSzYx/GOw2I6Lxc+QOQKSkrejlFfc1Fnjvl2y4Kw4E+Yu5v7L0WjwTk2ELZ6
fnTwaTomReIYTJyIBUbx8dUcRePRFpdc0t4A1gWqpsvpEvTmWRYF8VMWVc85OGbu
4aHBHfc/kLYDKoNcGO8HvGwn6AEA3y/GaooUwllHNRpSlgIik2cSPoAxdiUXghib
/f758ypGVgp4IdW90J5JqJPYGrgtkaZCVbwApPtKsXxKqphU7mMsz7k0v6/m03uK
fQNVVB0N95+AEgHvTPIyDRbkqpK1qy2N2u76d3NDErDZths9zwu1ZR2+kBAmfIoZ
CFSli0ye96Bt7SQtgnTvoQCrGwFSU++Y+BAffyqijadd1rdpxMjL2VvTLuPPZuNt
2CiW73MfLU8VcHmypeAZjOG+8o679Q39BViIlWunDgvVm9i9QL/TMIN7t7LbyvfF
GsmSKiQPfsZA46/ocL+zM22sKuqrHkM/tqj34hsPbC6j6q/vlPVd3ogIkPjVr0z2
/F2SozwW/VK2+eCSYWCBpSNBrKaNThTd9zA3qVZnu2SY1wfECz+TCl2A49CvnBJU
DShjQlEwk+FhInEODMe8kKcSMV9KBcJzxmQSpjTgnc9SgHLBabhaIBPqfBAje+ya
q9jOGA4iNtgH0e2ZCfA+2JQvbPXTt4IEXpb59Tpi0ZpXBvDsHcpy6YYzgGcSRS/S
CpF4THAe2/fXDf+wqz97xUivk1Jbmi5J4g5BdNs/5ZPSQIMqRk1jsMSWBhSjqvqh
XdiH5p591mEGFgzOlp4cjigTwjRvd0aGLjDewz8cTq0ac+Bhx2MkS525M90sBCHX
rg7N1J8y0pe761X7QhavSiuYb7UPalW5lSWgaPGNmTJCORu3PWPn30luU+//Lso2
mMpronZlPUl0RmjrfNErG3ozazyBCRUgqMPJZa33ygxLC0Tzt1/Aepf7Lt92aJYb
B7DPihndEX43CPfdUkP+VM3TD377/xHBc7PFcnRY3EZz9sBkg8au7kkajvffgSe7
4LDhOG+t1TBLQ/EGBfGad0hlTTha4z4xSNOUUtPPSmpow+6fAQOLmMyAXinwsh6c
g1lJUvj+/ZVMQgL6Nrsb87aP0NVY80v6RgOmHpccXomit4XQ6LXelz1g2CvDDRL9
1nsAvHBkbhtErrnAtlQgYZX9QVpSO3kcJ3T9q0degsuKEkRcxIwWhg1bE3MJjI08
FmZhgbf7moh5QqW3BP24BaxUrD40OBRh8ewiVScI0hh+CYVe3AiVBhBAOK5R0IJW
kbK/Ww3SPi6XRFuLSxSUb8070NPcmkkjDO2iktd7j9MvQ+JyKHLJamM1fjTzD4rM
yqQ8t5OjDczqYkmO8d0zs2epNK5kpUNq5+rzIvwUM2SuJrmiY6OtZ24wU3Lto/hU
siXeWNOQiiueWcZKQ7GEZgEnL3YVG0Jmd/uvZmqHFK6jqJxc9fYaqmGrgUGbZlFu
+8C7WGS+TE4CAw+xB3q7kBvpUym2Tfgf5AmGLDqqHkI8d23CFo1WR0yjPDAtpUmK
Sl4NIFCcTvaYwLQIlY71EJlAq1tqT8iqNSmeU6yRhGM1N6Arjerf0RLikimJtkaF
TplJ3RIdNeIn8TIqB25HzX9MidClH3E9tSDGX10V2KR2TwznKkVxRyQqu9JNkQsT
UNjoHlRvMl/yVizr+v4VgOVgYeNR3k0YI4b3J7FOumQSPdcu1ZKHz05gg9SIS1CI
ieSZmTK48zQxMYFGZdszYMipjqDFJR0VTlbIapQDvbCtHdoX15xg4AMz6Y+nzOH4
unJkQo6AiQ2rUwnQfbc16LOAF2TjGVehv89cizx0M5UG19DfloI7bW+KifZ6j3UU
iu6oUHWpCLTrRAUCkRxBiQ1SlBw2BEytjF1nNDJzCI0Q+dB3s4avhkxZawylWjFe
ujWFFjq4h6NE5XG/9JfIJdnR1h0PBMmFsaqIQQ411Rb9ahCNB9r8GbCObNTx7man
aKvjuXIRJMyFMitLvttft7+gIUlSbVOnSJWGbsKFgKAQUrZ8qmVa6Rdi95KqLd3U
ySqWvASX6sgdf5pfIoGVxBrsvaOPAFKMadct
=m6XJ
-----END PGP MESSAGE-----
NOTEBLOCK
