#!/bin/sh
internet="$(ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null && echo "online" || echo "offline")"
#internet="offline"

get_latest_version(){
	git clone https://github.com/oldwife/shell-notes /tmp/shell-notes
	file_path=/tmp/shell-notes/notes
}

if [[ "$internet" == "online" ]];then
	get_latest_version
else
	file_path=$0
fi

cat "$0" > ~/.cache/noteslocal.bak

header="$( cat "$file_path" | head -n +44 )" #:<<NOTEBLOCK
notes="$( cat "$file_path" | tail -n +45 | head -n -1 | gpg -dq )" #-----BEGIN PGP MESSAGE
echo "$notes" > /tmp/notes.sh
nvim /tmp/notes.sh
build_file() {
	echo "$header"
	cat /tmp/notes.sh | gpg -ac -o-
	echo "NOTEBLOCK"
}
build_file > "$file_path"
rm -rf /tmp/notes.sh

upload_notes(){
	cp -i /tmp/shell-notes/notes ~/.local/bin/
	cd /tmp/shell-notes
	git add .
	git commit --message "$(date)"
	git push -uf origin main
	rm -rf /tmp/shell-notes
}

if [[ "$internet" == "online" ]];then
	upload_notes
fi

# LINE 30
:<<NOTEBLOCK
-----BEGIN PGP MESSAGE-----

jA0ECQMIQaJ0RgYc6xz50uoBmXUWn14El3nS7oXPGRaeKK53SUWigwhvy5lYfW6A
bpY69rCL+IvhOymvL5o+rO0UDG/HTaT5KdgxT3WpsJeVp61Qn1hPKLRpdOYtgfaR
dSEkxWvoEwlPnKEAUgV46nu+Idw+KmLVIkPnz/tOaxazAbxRWhJ5Zo7Mwcrj+eVz
SJ5ZDW5jlHxiV+ZXeDUtJt0iTBQ0GMLJKBBeXjaz9QUMxWxHELE75ScUOU2TEokP
vQAhh6KmwV6tE9l5TVMXYrnNwi4XMSQfj0uDIuU2WrL7jXkbqxodVQQgCn52dH93
v7dQcm6a664Ttu/5T2H3nt/I6lamSwdodMufRyrcorAj8Yu1CSSFajx7nZkvR7Vd
IlRfPO8s8OffYf4DrCVW8eDX3CyUGENzFpJ8RN6hoR22hnDmZKOYAy1va0ly9wyD
xvSHJaPlI07tqbn5+y001240FPflnYcL24J5z9DBpapML7fjTO/vdx9s4rF8Wpa3
eK9F+Bt2AuE0p+H54gQo2ezBH+ZXhkRr7KcIvnXcuH114zFaljNnNYVKzpjYFiev
0vSvWQrbRSR3b7F3hbhIJRar3muvMoV/8GL9+UgUdI4qVJ5DCO62fE8J98zvuhie
oFQO61lfw1h/LiilpPL3Sr8rPIUo1+tNmSq3qLVfcNyFhPqTsHqCB12uKuqe3JPE
3gjNjo5tdpSJksavn/l54fmVRJ6jl/r2YaoWLS1nix9KKft4bsjawWu6bNdRq4rV
ZLiA0yAu8bs1riQ0xZQU9QqSai+f/M1g3IUE9IvPUcC7glttFPfU/MlPU6AAluVD
TUzYe/M5VZTDZsPK3p0NZllZqR6M6zocsTtG8+2qbUfTsAcZxkg7dll97/YBxOk4
xvhasdHj4Vsk96bzRZGwRp+PAp6nA2wnZRrxBZ5UJhvHvgNYkWH8W+/U0iYLQuRa
vt7x5PkRU3HCY7UFerk/ylkI6xFV3TtzIdP2USNLjjX5UNyxMStRWX8B3EuhmixW
8mE2iZ/d+bVuvu5hl+HUW8fowI5wZPB2CwAN+1+iHaZyXHHOdAMYbxy84TuC8SRM
1IeHVnXxxK1z7pbokK1JXc/1p74LGsR3v4MQmoMOT8u7PHGWLa/FfzV54FYoH7sO
qSgUx3vFfN7VVFBtWRJS1vePQWQzyzOPt+yfF3Uj6bcgHWK+d/o9xIUIOW1RqlJu
/QvcyLkqKo+/gUWibdJUG4HpW//znViO4uCMzFi6poVhcBQZmQEJ7/9FU8gYSLI8
IwllLkKCcFXCp3Km98OesWnWyX/6cMCCri5pzZFNJ8aF4gkktwKKBc0e5yaROw7c
R3kIbgo1AHbtJDcGjW43lSXa0QtbrclKDSIDBUbUDBQR6oM02+FB3OcugA67yvPW
OsHXh2PCXvrS/29y+w5ZzSQXu4E7TRRlQWOBDZIl0P5DDmwavNVPEYc+s+nESUZP
Dz7BlEShRsIJXrdSX2aw3v5Ucc4H4YXa8SlFMvvnJGhqNshy4FRWSw8AtxZ+N97t
glrg3SqFlsPeIYPaqbfJvEimmYwgWQpmcXwL90NZiUNLm8hglPfLDscDeM1KnjTJ
CFhfMWvvbQTOktfeDr+tIq2AeSg4ipsFwpl8PaNmUzbuozhuDE1PWPomxMRRxry1
3bm1u+ldJK247V0QsRarxGF8qtPAX9etQQiDXkEd4Z9FRvUYqeli6LvAbuWFrypK
XTJnacwZIUDbwKdxdHRp1CUrUNWqMGUe9+2nfPnRI5+C2ZVbO3b8bQ+HIpHm+vKN
GoOwjbAwFYGdirDq+kUq8XzZGRaslDz5HpKc+oMfnao496vOqVHqX2Wu5XENMg+P
09F8ocMqyeciTTF82vYJzv772QA3Biyabify3KRLukJr5Xykx4ift/yLhkCM8H1Z
k7XgyHS5AfdDkucLYAKy4XbApUoZzUb5LA7/myQWMTSZnMA7UUHEwHCmKramHFX8
lHkwEmvjL8wV+QbbUl2wzOu6qJRPUQaBtrPDB/af3vGTokfWFWVkw9Ygd71iYyLw
cZUTGqSJLcimS17vCNa5oHNprnnQ7Y+E5U9EGPD0uf4gHXXXKY0j3pHBL6xrzDeK
uTcZqFZfBlRFKSV67mlnYmDOILtpdYtwgK/QZnGjx/4OqT5XnacvcTBzCb0QqsSy
Dl3I6JYAN/wDNBAvbfwo399JuWZqtU2ziEh46tSIGP4OcARQdSRUmUpb1yd3onYl
CldLKsRpaIYge0Wq0LQM35RgtGf81VlTZOWnyR9EdMUS4n5B3VnJ+O2ja4ZW+nz3
nMgsHTnHlM6DWQNkHB4ppL4bmk6N3eNC+Ad2D0ErCrbNwsU8Q09AZ/cgzNDJ4NjD
wi0ZKCi2UnY6PxsuQlJz2aNhIgbldVOd1T1DKk0mc4FdlXhNhZForqPacCKcsZR+
De33TBN+2jlSEoQVMXFe9q6T+r9jGaRIkYpd71+k5WF8od5f5gLACvU/RPxYnA1S
K9A7+3hu51xNcvRmRymqGoVpx1U0IMqady/cAk2wwpkIofWsPkWhIUBZtEOsOj0h
l6YtmLlK67reNoztpxDgQVGDsRh5Ev4KI6F2WfoRWj/zhuw0ljH6PobuV03LFQNL
rnu3+mx/ksnIdzeeFEhd+f6ex9KA9SDZ9nNPGAOhWpEToo+6eL+/vCS2AoaMKOGN
+GWJ3MXSE9F1FfBgpULNiGNT0oUKv6R2Rtd4SnuhaqqY/LuuWFPtGFIIUN/SUHbG
OEGrsys1ZB8G7jGAJgUBgXnQHb7F8VCTzwguh/3KM4bvzJjj06LwJAQr6cWfSwfq
ga6C9QnyHGyzmMaxYJ/gwM/DxGed+jKZV7/rEWMjmLEWT9bNC6kYOo/Nh0mUQKxk
HWd18idcPUtEoWIAhFWafrbyowZJjZI+LnuPymueISIp0myr0qNx1BpmaoKfLteE
NLFlmJJuAr7oidQQ4r7sNDst2r1y6Nzr7rN5+Lje
=Kr4O
-----END PGP MESSAGE-----
NOTEBLOCK
